[package]
name = "backshot_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
# OpenGL reqs
gl = "0.14.0"
glm = "0.3.0"
sdl2 = { version = "0.37.0", features = ["ttf"] }
# Macro helpers
paste = "1.0.15"
# Imgui overlay debug ui
imgui = "0.12.0"
imgui-sdl2-support = "0.13.0"
